import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider"
import { Roboto } from "next/font/google"
import Nav from "@/components/navigation/nav";
import { Toaster } from 'sonner'


const roboto = Roboto({
    weight: ["400", "500", "700", "900"],
    subsets: ["latin"]
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={roboto.className}>
                <div className="flex-grow px-6 md:px-12 mx-auto max-w-6xl">
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <Nav />
                        <Toaster />
                        {children}
                    </ThemeProvider></div>
            </body>
        </html>
    );
}
